Iterarng over nd-array

Iterating for 1 & 2 Dimentional array using static loop(for loop) & nditer methods

In [42]:
import numpy as np
# Creating 1-Dimentional array and printing
a_1d = np.array([1,2,3,4,5])
a_1d


array([1, 2, 3, 4, 5])

In [43]:
# Finding dimention of array a_1d
a_1d.ndim

1

In [44]:
# Iterating using static loop (for loop)
for x in a_1d:
      print(x)

1
2
3
4
5


In [57]:
# Iterating using nditer
for x in np.nditer(a_1d):
  print(x)

1
2
3
4
5


In [45]:
# Creating 2-Dimentional array and printing
a_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
# Finding dimention of array a_2d
a_2d.ndim

2

In [50]:
# Iterating using static loop (for loop)
for x in a_2d:
  for y in x:
      print(y)

1
2
3
4
5
6
7
8
9
10


In [58]:
# Iterating using nditer
for x in np.nditer(a_2d):
  print(x)

1
2
3
4
5
6
7
8
9
10


Iterating N-dimentional array

In [48]:
# Creating 3-Dimentional array and printing
a_3d =np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
a_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [51]:
# Finding dimention of array a_3d
a_3d.ndim

3

In [52]:
# Iterating using static loop (for loop)
for x in a_3d:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [32]:
# Iterating using nditer
for x in np.nditer(a_3d):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [66]:
# Creating 3-Dimentional array and printing
a_3d1 = np.array([[[1, 2, 3,4,5], [6,7,8,9,10],[11,12,13,14,15]], [[16,17,18,19,20], [21,22,23,24,25],[26,27,28,29,30]],[[31,32,33,34,35],[36,37,38,39,40],[41,42,43,44,45]]])
print(a_3d1)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]]


In [67]:
# Finding dimention of array a_3d
a_3d1.ndim

3

In [60]:
# Iterating using static loop (for loop)
for x in a_3d1:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45


In [59]:
# Iterating using nditer
for x in np.nditer(a_3d1):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45


In [64]:
# Creating 4-Dimentional array and printing
a_4d = np.array([[[[1],[2],[3],[4]]]])
a_4d

array([[[[1],
         [2],
         [3],
         [4]]]])

In [68]:
# Finding dimention of array a_4d
a_4d.ndim

4

In [71]:
# Iterating using static loop (for loop)
for a in a_4d:
      print(a)

      

[[[1]
  [2]
  [3]
  [4]]]


In [72]:
# Iterating using nditer
for x in np.nditer(a_4d):
  print(x)

1
2
3
4


In [76]:
# Creating 5-Dimentional array and printing
a_5d = np.array([[[[[1,6],[2,7],[3,8],[4,9],[5,10]]]]])
a_5d

array([[[[[ 1,  6],
          [ 2,  7],
          [ 3,  8],
          [ 4,  9],
          [ 5, 10]]]]])

In [77]:
# Finding dimention of array a_5d
a_5d.ndim

5

In [80]:
# Iterating using static loop (for loop)
for h in a_5d:
      print(h)


[[[[ 1  6]
   [ 2  7]
   [ 3  8]
   [ 4  9]
   [ 5 10]]]]


In [82]:
# Iterating using nditer
for x in np.nditer(a_5d):
  print(x)

1
6
2
7
3
8
4
9
5
10
